server:
  port: 9191
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: CRDIT-MICROSERVICE
          uri: http://localhost:8092/
          predicates:
            - Path=/credits/*,/offer/*,/garantor/*,/repayment/**,/credits/*/*,/garantor/*/*
        - id: FUNDME
          uri: http://localhost:8093/
          predicates:
            - Path=/supplier/*,/user/*,/product/* 
            
            
#eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost